name: ESLint Check

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    eslint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '22'

            - name: Install dependencies
              run: npm install

            - name: Run ESLint on pages and API routes
              run: npx eslint pages/**/*.js pages/**/*.jsx pages/**/*.ts pages/**/*.tsx api/**/*.js api/**/*.ts src/**/*.js src/**/*.ts src/**/*.jsx src/**/*.tsx
